name: equations
description: An equation solving library written in Dart. It also works with complex numbers and fractions.
version: 2.2.0
repository: https://github.com/albertodev01/equations
homepage: https://fluttercompletereference.com/

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  fraction: ^3.0.1
  petitparser: ^4.1.0

dev_dependencies:
  coverage: ^1.0.3
  test: ^1.17.10