const englishStrings = {
  'appTitle': 'Equations solver',
  'polynomials': 'Polynomials',
  'functions': 'Functions',
  'systems': 'Systems',
  'integrals': 'Integrals',
  'interpolation': 'Interpolation',
  'other': 'Other',
  'firstDegree': 'Linear',
  'secondDegree': 'Quadratic',
  'thirdDegree': 'Cubic',
  'fourthDegree': 'Quartic',
  'anyDegree': 'Any',
  'solution': 'Solution',
  'solutions': 'Solutions',
  'chart': 'Chart',
  'solve': 'Solve',
  'clean': 'Clean',
  'cancel': 'Cancel',
  'no_solutions': 'No solutions to display.',
  'no_chart': 'No chart to plot.',
  'no_discriminant': 'No discriminant.',
  'polynomial_error': "One or more coefficients aren't valid.",
  'wrong_input': 'Invalid input',
  'tap_more': 'Tap to see more details',
  'discriminant': 'Discriminant',
  'fraction': 'Fraction',
  'single_point': 'Single point',
  'bracketing': 'Bracketing',
  'precision': 'Precision',
  'convergence': 'Convergence',
  'efficiency': 'Efficiency',
  'not_computed': 'Not computed',
  'nonlinear_error': 'Wrong equation or parameters format.',
  'row_reduction': 'Row reduction',
  'factorization': 'Factorization',
  'iterative': 'Iterative',
  'size': 'Size',
  'matrix_size1': '1x1 matrix',
  'matrix_size2': '2x2 matrix',
  'matrix_size3': '3x3 matrix',
  'matrix_size4': '4x4 matrix',
  'matrix_description': 'The matrix with the equations coefficients',
  'vector_description': 'The vector with the known values',
  'sor_w': 'Relaxation factor',
  'jacobi_initial': 'Initial guesses vector',
  'singular_matrix_error':
      'The system cannot be solved because the matrix is singular!',
  'invalid_values': "One or more values aren't correct.",
  'matrices': 'Matrices',
  'linear': 'Linear',
  'analyze': 'Analyze',
  'results': 'Results',
  'wait_a_moment': 'Wait a moment...',
  'rank': 'Rank',
  'trace': 'Trace',
  'transpose': 'Transpose',
  'determinant': 'Determinant',
  'inverse': 'Inverse',
  'cofactor': 'Cofactor',
  'characteristicPolynomial': 'Characteristic polynomial',
  'eigenvalues': 'Eigenvalues',
  'properties': 'Properties',
  'complex_numbers': 'Complex numbers',
  'phase': 'Phase',
  'abs': 'Modulus / absolute value',
  'conjugate': 'Conjugate',
  'reciprocal': 'Reciprocal',
  'sqrt': 'Square root',
  'length': 'Length',
  'angle_deg': 'Angle (degree)',
  'angle_rad': 'Angle (radians)',
  'polar_coordinates': 'Polar coordinates',
  'yes': 'Yes',
  'no': 'No',
  'diagonal': 'Diagonal',
  'symmetric': 'Symmetric',
  'identity': 'Identity',
  'url_error': "This page doesn't exists!",
  'version': 'Version',
  'input_allowed_values': 'Allowed values',
  'input_allowed_numbers': ' - Decimal and integer numbers.',
  'input_allowed_fractions': ' - Fractions.',
  'input_allowed_constants':
      ' - Constants: pi (3.1415), e (2.7182) and sqrt2 (1.4142).',
  'input_allowed_functions': 'The equation f(x) allows these functions:',
  'input_allowed_multiplication_sign':
      'The multiplication requires the sign. For example:',
  'more_digits': 'No approximation: ',
  'nonlinear_fail_converge': "The method didn't converge to a solution."
};
