name: equations_ci

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types:
      - opened

jobs:
  integration_test_windows_flutter_example:
    name: Flutter example - Integration test on Windows
    runs-on: windows-latest
    defaults:
      run:
        working-directory: example/flutter_example
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - uses: subosito/flutter-action@v2.6.1
        with:
          channel: 'stable'

      - name: Installing dependencies
        run: flutter pub get

      - name: Runing unit, widget and golden tests
        run: flutter test -d windows .\integration_test\
