name: equations_ci

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types:
      - opened

jobs:
  flutter_example_integration_tests_windows:
    name: Flutter example - integration tests on Windows
    runs-on: windows-latest
    defaults:
      run:
        working-directory: example/flutter_example
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - uses: subosito/flutter-action@v2.6.1
        with:
          channel: 'stable'

      - name: Installing dependencies
        run: flutter pub get

      - name: Runing unit, widget and golden tests
        run: flutter test .\integration_test -d windows

  flutter_example_integration_tests_macos:
    name: Flutter example - integration tests on macOS
    needs: [flutter_example_integration_tests_windows]
    runs-on: macos-latest
    defaults:
      run:
        working-directory: example/flutter_example
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - uses: subosito/flutter-action@v2.6.1
        with:
          channel: 'stable'

      - name: Installing dependencies
        run: flutter pub get

      - name: Runing unit, widget and golden tests
        run: flutter test .\integration_test -d macos

  flutter_example_integration_tests_linux:
    name: Flutter example - integration tests on Linux
    needs: [flutter_example_integration_tests_macos]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: example/flutter_example
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - uses: subosito/flutter-action@v2.6.1
        with:
          channel: 'stable'

      - name: Installing dependencies
        run: flutter pub get

      - name: Runing unit, widget and golden tests
        run: flutter test .\integration_test -d linux